from pathlib import Path
import re

ROOT = Path(".")

def assemble(target_path: str, part_paths: list[str]) -> None:
    target = ROOT / target_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("".join((ROOT / part).read_text(encoding="utf-8") for part in part_paths), encoding="utf-8")

def replace(path: str, old: str, new: str, count: int = 1) -> None:
    target = ROOT / path
    source = target.read_text(encoding="utf-8")
    found = source.count(old)
    if found < count:
        raise SystemExit(f"{path}: expected {count} occurrences, found {found}: {old[:100]!r}")
    target.write_text(source.replace(old, new, count), encoding="utf-8")

def regex(path: str, pattern: str, replacement: str, count: int = 1) -> None:
    target = ROOT / path
    source = target.read_text(encoding="utf-8")
    updated, matches = re.subn(pattern, replacement, source, count=count, flags=re.S)
    if matches != count:
        raise SystemExit(f"{path}: expected {count} regex matches, found {matches}: {pattern[:100]!r}")
    target.write_text(updated, encoding="utf-8")

assemble(
    "apps/web/src/patterns/basePatternDrafting.ts",
    [
        "scripts/prompt06-basePatternDrafting.part00.txt",
        "scripts/prompt06-basePatternDrafting.part01.txt",
        "scripts/prompt06-basePatternDrafting.part02.txt",
    ],
)
assemble(
    "apps/web/src/patterns/basePatternDrafting.test.ts",
    ["scripts/prompt06-basePatternDrafting.test.txt"],
)

replace('apps/web/src/patterns/templateCatalog.ts', 'import {\n  BODY_MEASUREMENT_CATALOG,\n  createMeasurementProfile,\n  measurementProfileSnapshot,\n  measurementProfileToBodyMeasurements,\n  type MeasurementProfile,\n} from "../domain/parametricMeasurements";\n', 'import {\n  BODY_MEASUREMENT_CATALOG,\n  createMeasurementProfile,\n  measurementProfileSnapshot,\n  measurementProfileToBodyMeasurements,\n  type MeasurementProfile,\n} from "../domain/parametricMeasurements";\nimport {\n  BASE_PATTERN_METADATA,\n  draftBasePattern,\n  isBasePatternTemplateId,\n  type PatternValidationStatus,\n} from "./basePatternDrafting";\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', 'export type PatternTemplateId =\n  | "tshirt"\n', 'export type PatternTemplateId =\n  | "bodice-block"\n  | "tshirt"\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', '  status: "ready" | "development";\n  requiredMeasurements: string[];\n', '  status: "available" | "development";\n  validationStatus: PatternValidationStatus;\n  reviewNotes: string[];\n  requiredMeasurements: string[];\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', 'export const TEMPLATE_FORMULA_VERSIONS: Record<PatternTemplateId, string> = {\n  tshirt: "tshirt@1",\n  blouse: "blouse@1",\n  "straight-skirt": "straight-skirt@1",\n  "mini-skirt": "mini-skirt@1",\n', 'export const TEMPLATE_FORMULA_VERSIONS: Record<PatternTemplateId, string> = {\n  "bodice-block": BASE_PATTERN_METADATA["bodice-block"].templateVersion,\n  tshirt: BASE_PATTERN_METADATA.tshirt.templateVersion,\n  blouse: BASE_PATTERN_METADATA.blouse.templateVersion,\n  "straight-skirt": BASE_PATTERN_METADATA["straight-skirt"].templateVersion,\n  "mini-skirt": BASE_PATTERN_METADATA["mini-skirt"].templateVersion,\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', 'export const PATTERN_TEMPLATES: readonly PatternTemplateSummary[] = [\n  {\n    id: "tshirt",\n', 'export const PATTERN_TEMPLATES: readonly PatternTemplateSummary[] = [\n  {\n    id: "bodice-block",\n    name: "Corpo básico",\n    category: "Parte de cima",\n    description: "Bloco de referência com frente e costas distintas.",\n    pieces: "Frente e costas",\n    status: "available",\n    validationStatus: BASE_PATTERN_METADATA["bodice-block"].validationStatus,\n    reviewNotes: BASE_PATTERN_METADATA["bodice-block"].notes,\n    formulaVersion: TEMPLATE_FORMULA_VERSIONS["bodice-block"],\n    requiredMeasurements: ["busto", "cintura", "quadril", "ombro", "cava", "frente e costas"],\n    estimatedMeasurements: ["pescoço", "inclinação do ombro", "altura do quadril"],\n  },\n  {\n    id: "tshirt",\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', 'status: "ready",', 'status: "available",', count=5)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "tshirt",.*?status: "available",)', '\\1\\n    validationStatus: BASE_PATTERN_METADATA["tshirt"].validationStatus,\\n    reviewNotes: BASE_PATTERN_METADATA["tshirt"].notes,', count=1)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "blouse",.*?status: "available",)', '\\1\\n    validationStatus: BASE_PATTERN_METADATA["blouse"].validationStatus,\\n    reviewNotes: BASE_PATTERN_METADATA["blouse"].notes,', count=1)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "straight-skirt",.*?status: "available",)', '\\1\\n    validationStatus: BASE_PATTERN_METADATA["straight-skirt"].validationStatus,\\n    reviewNotes: BASE_PATTERN_METADATA["straight-skirt"].notes,', count=1)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "mini-skirt",.*?status: "available",)', '\\1\\n    validationStatus: BASE_PATTERN_METADATA["mini-skirt"].validationStatus,\\n    reviewNotes: BASE_PATTERN_METADATA["mini-skirt"].notes,', count=1)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "straight-pants",.*?status: "available",)', '\\1\\n    validationStatus: "experimental",\\n    reviewNotes: ["Fora do escopo do Prompt 6; o gerador de calça permanece simplificado e sem revisão manual."],', count=1)
regex('apps/web/src/patterns/templateCatalog.ts', '(id: "basic-jacket",.*?status: "development",)', '\\1\\n    validationStatus: "experimental",\\n    reviewNotes: ["Indisponível até possuir bloco próprio e revisão manual."],', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', '  if (summary.status !== "ready") throw new RangeError(`${summary.name} está em desenvolvimento.`);\n\n  const fabric = createDefaultFabricSource();\n  const pieces = generator(measurements).map((piece) => ({\n', '  if (summary.status !== "available") throw new RangeError(`${summary.name} está em desenvolvimento.`);\n\n  const baseDraft = isBasePatternTemplateId(templateId)\n    ? draftBasePattern(templateId, measurements)\n    : undefined;\n  const fabric = createDefaultFabricSource();\n  const pieces = (baseDraft?.pieces ?? generator(measurements)).map((piece) => ({\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', '      variables: [],\n      constructionGraph: createInitialConstructionGraph(BODY_MEASUREMENT_CATALOG.map((entry) => entry.key)),\n      generations: pieces.map((piece) => ({\n', '      variables: baseDraft?.variables ?? [],\n      constructionGraph: baseDraft?.constructionGraph\n        ?? createInitialConstructionGraph(BODY_MEASUREMENT_CATALOG.map((entry) => entry.key)),\n      generations: pieces.map((piece) => ({\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', '        defaultValues: snapshot.defaults,\n      })),\n', '        defaultValues: snapshot.defaults,\n        ...(baseDraft ? {\n          constructionSystem: baseDraft.metadata.constructionSystem,\n          validationStatus: baseDraft.metadata.validationStatus,\n          componentValidation: baseDraft.metadata.componentStatus,\n          requiredMeasurements: baseDraft.metadata.requiredMeasurements,\n          estimatedMeasurements: baseDraft.metadata.estimatedMeasurements,\n          ease: baseDraft.metadata.ease,\n          limits: baseDraft.metadata.limits,\n          manualReview: baseDraft.metadata.manualReview,\n        } : {}),\n      })),\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', '    ease: { bustMm: 80, waistMm: 60, hipMm: 80, sleeveMm: 50 },\n', '    ease: baseDraft?.ease ?? { bustMm: 80, waistMm: 60, hipMm: 80, sleeveMm: 50 },\n', count=1)
replace('apps/web/src/patterns/templateCatalog.ts', 'const GENERATORS: Record<PatternTemplateId, TemplateGenerator> = {\n  tshirt: (measurements) =>\n', 'const GENERATORS: Record<PatternTemplateId, TemplateGenerator> = {\n  "bodice-block": (measurements) => draftBasePattern("bodice-block", measurements).pieces,\n  tshirt: (measurements) =>\n', count=1)
replace('apps/web/src/domain/parametricMeasurements.ts', '  defaultValues: Partial<Record<BodyMeasurementKey, number>>;\n}\n', '  defaultValues: Partial<Record<BodyMeasurementKey, number>>;\n  constructionSystem?: string;\n  validationStatus?: "experimental" | "geometrically-validated" | "manually-reviewed";\n  componentValidation?: Record<string, "experimental" | "geometrically-validated" | "manually-reviewed">;\n  requiredMeasurements?: BodyMeasurementKey[];\n  estimatedMeasurements?: BodyMeasurementKey[];\n  ease?: { bustMm: number; waistMm: number; hipMm: number; sleeveMm: number };\n  limits?: Record<string, number>;\n  manualReview?: boolean;\n}\n', count=1)
replace('apps/web/src/domain/patternDocumentV3.ts', '  type ConnectorRoleV3,\n', '  type ConnectorLandmarkV3,\n  type ConnectorRoleV3,\n', count=1)
regex('apps/web/src/domain/patternDocumentV3.ts', 'function migrateSemanticConnectors\\(piece: PatternPiece\\): PatternConnectorV3\\[\\] \\{.*?\\n\\}\\n\\nfunction inferSemanticRole', 'function migrateSemanticConnectors(piece: PatternPiece): PatternConnectorV3[] {\n  const grouped = new Map<ConnectorRoleV3, NonNullable<PatternPiece["segments"]>>();\n  for (const segment of piece.segments ?? []) {\n    const role = CONNECTOR_ROLE_BY_SEGMENT_ROLE[segment.role];\n    if (!role) continue;\n    const current = grouped.get(role) ?? [];\n    current.push(segment);\n    grouped.set(role, current);\n  }\n  return [...grouped.entries()].map(([role, segments]) => ({\n    id: `${piece.id}:connector:${role}`,\n    role,\n    ranges: segments.map((segment) => ({\n      pieceId: piece.id,\n      edgeId: segment.id,\n      startT: 0,\n      endT: 1,\n    })),\n    landmarks: semanticConnectorLandmarks(piece.id, role, segments.length),\n    direction: "forward",\n    metadata: { landmarkSource: "semantic-role-v1" },\n  }));\n}\n\nfunction semanticConnectorLandmarks(\n  pieceId: string,\n  role: ConnectorRoleV3,\n  rangeCount: number,\n): ConnectorLandmarkV3[] {\n  const lastRange = Math.max(0, rangeCount - 1);\n  const landmarks: ConnectorLandmarkV3[] = [\n    { id: `${pieceId}:${role}:start`, kind: "start", rangeIndex: 0, t: 0 },\n    { id: `${pieceId}:${role}:end`, kind: "end", rangeIndex: lastRange, t: 1 },\n  ];\n  if (role === "front-armhole" || role === "sleeve-cap-front") {\n    landmarks.push({\n      id: `${pieceId}:${role}:front-notch`,\n      kind: "notch",\n      rangeIndex: 0,\n      t: rangeCount > 1 ? 1 : 0.62,\n      label: "Pique frontal",\n    });\n  }\n  if (role === "back-armhole" || role === "sleeve-cap-back") {\n    landmarks.push(\n      {\n        id: `${pieceId}:${role}:back-notch-1`,\n        kind: "notch",\n        rangeIndex: 0,\n        t: rangeCount > 1 ? 0.74 : 0.42,\n        label: "Primeiro pique traseiro",\n      },\n      {\n        id: `${pieceId}:${role}:back-notch-2`,\n        kind: "notch",\n        rangeIndex: lastRange,\n        t: rangeCount > 1 ? 0.28 : 0.68,\n        label: "Segundo pique traseiro",\n      },\n    );\n  }\n  if (role === "shoulder") {\n    landmarks.push({\n      id: `${pieceId}:${role}:balance`,\n      kind: "balance",\n      rangeIndex: 0,\n      t: 0.5,\n      label: "Marca de ombro",\n    });\n  }\n  return landmarks;\n}\n\nfunction inferSemanticRole', count=1)
replace('apps/web/src/components/PatternLibraryDialog.tsx', '              disabled={template.status !== "ready"}\n', '              disabled={template.status !== "available"}\n', count=1)
replace('apps/web/src/components/PatternLibraryDialog.tsx', '                {template.status === "development" ? (\n                  <small className="template-status">Em desenvolvimento</small>\n                ) : null}\n', '                <small className="template-status">\n                  {template.status === "development"\n                    ? "Em desenvolvimento"\n                    : validationLabel(template.validationStatus)}\n                </small>\n                <small>{template.reviewNotes[0]}</small>\n', count=1)
replace('apps/web/src/components/PatternLibraryDialog.tsx', '});\n', '});\n\nfunction validationLabel(status: "experimental" | "geometrically-validated" | "manually-reviewed"): string {\n  if (status === "manually-reviewed") return "Revisado manualmente";\n  if (status === "geometrically-validated") return "Validado geometricamente · prova manual pendente";\n  return "Experimental · não validado manualmente";\n}\n', count=1)
replace('apps/web/src/patterns/templateCatalog.test.ts', '  it("offers the six essential editable bases", () => {\n    expect(PATTERN_TEMPLATES.map((template) => template.id)).toEqual([\n      "tshirt",\n', '  it("offers the seven essential editable bases", () => {\n    expect(PATTERN_TEMPLATES.map((template) => template.id)).toEqual([\n      "bodice-block",\n      "tshirt",\n', count=1)
replace('apps/web/src/patterns/templateCatalog.test.ts', 'PATTERN_TEMPLATES.filter((template) => template.status === "ready")', 'PATTERN_TEMPLATES.filter((template) => template.status === "available")', count=1)
replace('apps/web/src/patterns/templateCatalog.test.ts', '    expect(top.pieces.every((piece) => piece.grainline)).toBe(true);\n', '    expect(top.pieces.every((piece) => piece.grainline)).toBe(true);\n    expect(top.parametric?.templateVersion).toBe("tshirt@2");\n    expect(top.parametric?.variables.length).toBeGreaterThan(10);\n', count=1)

print("Prompt 6 implementation patch applied")
