from pathlib import Path
path = Path('apps/web/src/garment3d/ConstraintSpatialAssembly.ts')
text = path.read_text()
old = '''  const intrinsic = measureIntrinsicDistortion({\n    positions,\n    structuralConstraints: state.structuralConstraints,\n    instances: state.instances,\n  });\n  return {\n    normalizedResidual: weightTotal > 0 ? weightedNormalized / weightTotal : 0,\n    meanResidualMm: weightTotal > 0 ? weightedResidualM / weightTotal * 1000 : 0,\n    maxResidualMm: maxResidualM * 1000,\n    nonPlanarityRad: componentNonPlanarity(positions, state, component),\n    coarseOverlapScore: componentOverlapScore(positions, state, component),\n    intrinsicDistortion: intrinsic.maxRelativeDistortion,'''
new = '''  const intrinsicDistortion = component.nodeIds.length === 1\n    ? measureIntrinsicDistortion({\n        positions,\n        structuralConstraints: state.structuralConstraints,\n        instances: state.instances,\n      }).maxRelativeDistortion\n    : measurePhysicalEuclideanIntrinsicDistortion(positions, state, component);\n  return {\n    normalizedResidual: weightTotal > 0 ? weightedNormalized / weightTotal : 0,\n    meanResidualMm: weightTotal > 0 ? weightedResidualM / weightTotal * 1000 : 0,\n    maxResidualMm: maxResidualM * 1000,\n    nonPlanarityRad: componentNonPlanarity(positions, state, component),\n    coarseOverlapScore: componentOverlapScore(positions, state, component),\n    intrinsicDistortion,'''
assert old in text
text = text.replace(old, new, 1)
marker = '''function componentNonPlanarity(\n  positions: Float32Array,'''
helper = '''function measurePhysicalEuclideanIntrinsicDistortion(\n  positions: Float32Array,\n  state: GarmentAssemblyState,\n  component: GarmentSpatialConstraintComponent,\n): number {\n  const members = new Set(component.nodeIds);\n  const instanceByParticle = new Map<number, string>();\n  for (const instance of state.instances) {\n    if (!members.has(instance.id)) continue;\n    for (let local = 0; local < instance.vertexCount; local += 1) {\n      instanceByParticle.set(instance.particleStart + local, instance.id);\n    }\n  }\n  let maximum = 0;\n  for (const constraint of state.structuralConstraints) {\n    const instanceA = instanceByParticle.get(constraint.a);\n    const instanceB = instanceByParticle.get(constraint.b);\n    if (!instanceA || instanceA !== instanceB || constraint.restLength <= EPS) continue;\n    const offsetA = constraint.a * 3;\n    const offsetB = constraint.b * 3;\n    const current = Math.hypot(\n      positions[offsetB] - positions[offsetA],\n      positions[offsetB + 1] - positions[offsetA + 1],\n      positions[offsetB + 2] - positions[offsetA + 2],\n    );\n    maximum = Math.max(maximum, Math.abs(current - constraint.restLength) / constraint.restLength);\n  }\n  return maximum;\n}\n\n'''
assert marker in text
text = text.replace(marker, helper + marker, 1)
path.write_text(text)
print('Prompt 10.6 Euclidean intrinsic candidate scoring applied')
